language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: dgUxXBRefLShGPGO4qY2JkoMni6bBuyJNq/0vn5C3vzADihFP+Ljs9GiBnsqPToEpOKkQ/G9Xrpp/BgNeeh/CrdlJsJuEBgeyFacoS9cO9ayGCmAx/tAAXZRpMaG9kG2yS6NEQL8AluTBQYJ+GatgOXcFxclxfKopOkjPAE6gnlzXKyUQaCA2QxuMBOu/0jgOg3J6vXIsrkkbUnMRv/mRCaDa30JkwvKnH+n/TqH1FqRAYpmFwIa/L1na2rIQK92qCkjSpZZeckCXnJJwi6PaHbBgcIOAV41E0xXu7p6WUa4bvj5ikJi9uXBYGBI2IBTQn1YEOFFql4Wc1dZ+rS7j2WnYvfiskKjzJJeTDcu6NXNBJDtat+JX0JiREGoGveyWJVIf4neE4u7hlnEWo7NgH8IPgKK7OJTplCObAdG0sSBCqxlhHwiAmE2GSLf3/bsTNm42xGLjbS0t15BmHQh7zV9TwpK79ct3qkiSbuPixhpnTlVKLN/i1i8BZ860xzbWM8uSgtje5X8nWK3M7IXen4t4UIDGay/OdyOUBNpYCXGnslkH7qoeL/2WeLCjS/k5XxXirucuRNhDkTzWECMh3WF3TsKgOw71COJkM/tUX3UDVd09i2IaT0wJQi+FBaMNLS0qUtX0EuaRyPrdQogDEXV9vFhKH3WCyMDWcnOKNw=
  app: portfolio-jcpascolo
