language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: wBWXkkxMMmE/i+aG0skSTxM4J0ao/s5PPVuyPZXZZlW0zwVRVFRqs6HQN/wkrpqDcnp+mTHuoDZGfvdyTLRXNOnOYskwmoaLeySqY8g6Z0v1XdgjOXMabOKOFKCD9F6Yv//ocKagRzFJtx19Ch35G3pEPqkBkQJBoDwvusFzoTw+5KwsNYQTWOcdnsPPVDpNoImgSvqpVf+KNcfoNU4I1mhAtPvSl0EhgQqvSK7CcX9AA+61syliF0u8PTIkZILn2dME4E6nEFgLLEFqKdDSoymrNCJJazPTn8K+2aJ2+cIX6Ea37S23nUL2hHJwSYmyNsZGOGukf2cr60JJEGNFoZm709kbCGRVR+rhXuFME4yXRX01ij1X1b8yd/sMneUkCeu0LNumxI6hCQ0dx2gTVUqCdg3Y6Jme5eTX5XkvsJBLSRZ2jAUEiy2dd2U8yAT5CO/FI6h6vWs6JpElCchtsSmw1875tDSN39ERTZ6VsJZsxci14PWADbQHTjMK4IVM1OQSzukGSOIO+NYj/bh28rOPYHjlCuA2SvRIoW5HPx4jaH5A47khG7RE2oYwS02dXsox2QRA2BWjL7iOc0IY5W58i6l60oQSwfHWLaWA+dV6rujpcPU5XJVRwS2Apvwm//Lb1M8pAwlYbXwVLfEKzTcnKvCtmdmI3d10pInmbAE=
  app: portfolio-jcpascolo
  on: master
