language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: y/r2CNBHhQF4dva1t2CVpvyvJRQ/BEj9PN57BxXP+WqbxqQRGfkgg+W6SoFxADc3ZM/bxOD+Be856mUT+xKG3PcBET8tsYmBGkeFPptW8txSJhUFV50vJ5xArTvzn3OAKva7aNFPFsHFMsnIaNhNvzYJ16kt6Jw0HUHv24HcdsK+ylir8eUr9N+NyziNxNhhXy+EoAxhcy3+z7Cd6Kf1fmigGdts/dykaMi5Alq43gE6P6gxhoU2k7b1K6rZuCTW2WtbV7j8eTSun/PaCkARKLwyRjX7QtsWNqNGKaAJo4192rXZ7sO1bsOOXx/lg6bCibC/06MKlG2nzJ50dZ8iqA7ry6Qvddd3mqcYfYTFcRglWIEggsbLSDaxf5ANNYDg65p8Tl8H3ku9aRpCyc623fpvLRHRIemO8q17TQbcGRb4dshxeWQpb9AXZWysXjRQl6yUQR9eGyX8hauX4M9e8PsMMEh1+/MGv/CuvgOL13KR5QdSlX3aafaOupZPA4IdvJZzk14Jsyw7N8o5Pwin94gGE2d/n9eEcbxQLwRf2+ANeTJ20UuGjKm7T35ss9A5Z9bZGFA3M1bH9rFKzjjJxTz+4eQPTwWh4Gxe59cq98WKiEdGzkf7wjrhCDiPpjs90ZMd1ugRhnDqPaT/m+q3ZsFzaQOiAuBnIg/vcVI8D5M=
  app: portfolio-jcpascolo
