language: node_js
node_js:
- node
branches:
  only:
  - master
script:
- npm install
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: PBJukpCh7PPJJ18fBnvp0HEC3Krcr2vODPIqPMOpuG/KejCYNWWQia8xKBfEh0TgrSKkqPn+rkf5eYlGODAnqpITFx+kP2AghkowSakUg6GewmXHb/cOH+1YyhAdq0cEe25StrS4Ymn4j6kHRwV6AdeXj3iie6dwIXIzwJCy6rgIA+rtn6coqgCrTK0i0AzwCc59VMWDNdRk21aGFtYWyL+Qh3ETRUDDRpYLUM3NY2DWIDGMkHktjXP5RXgWfs8GfrVgDkuZiYTQnGiJbvK/Q0+WEwkVg7p5p9/NANtKG73CMwuJStObDEqv+EpSVBpOIVmoei4YWS2+TehFZRoPwL8M4ye4HgJtkd1QrjSo6hd8zgvFWZn79OkMcgKKJA0+Qu8Jp4jNg/y9eSgzSL8VHAHcoSbE74ziO4lbMLwOnB5HLfHXznB3qFQIw6d1l7/8GkPHoxNzFd8vOcpE6Ve7LZV/ASEOTVS77Zp0PgybUjyJGkNU4ocGpgT3hYxlDXQ4nbFSj+Cgx4enQikn81tp/Lhr6DuOMJPdQZMw+v4ApnDhVGejh22YT7icZXoDmeHUuVuunNXTPJvEfJcnt/c6dLIiz0Sk90QU8om8COT1CmlG1m0wmoLmhK/N4VJjOJXNDoP2LhZm2wEoWw7Cn1OLG/ACGOMzcEW4aBPc7E1K3Fg=
  app: portfolio-jcpascolo
  on: master
